READ = "READ"
DELETE = "DELETE"
CREATE = "CREATE"
UPDATE = "UPDATE"
READ_MY_RECORDS = "READ_MY_RECORDS"
UPDATE_MY_RECORDS = "UPDATE_MY_RECORDS"
DELETE_MY_RECORDS = "DELETE_MY_RECORDS"

NOT_ALLOWED_ERROR = "User not allowed"
USER_NOT_FOUND_ERROR = "User not found"

ALL_PERMITS = [READ, DELETE, CREATE, UPDATE]
